### ISSUE TITLE
Possible missing princess boss?

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#25] opened 2016-08-22 12:10 UTC
Please see this:  https://www.twitch.tv/tristalmtg/v/85003967
Seed 42291642 - ultra, fast, no.  Full video here:  https://www.twitch.tv/tristalmtg/v/84987384

**Comment by mcgrew** [comment] 2016-10-01 20:24
What likely happened is he fought the same enemy that would have been the princess boss in the cave before walking to it's spot. This would have marked the enemy as defeated, since the game only checks the enemy type and map before marking it defeated. This would also happen in the original game if it were possible to encounter a green dragon in the swamp cave or a golem on the overworld.

Marking this as invalid ("not a bug") for now.

**Closed by mcgrew** 2016-10-01 20:24 UTC
